export const modelText = {
  zh: {
    notice: '模型声明与完整署名', manifest: '模型来源记录', viewerCredits: '3D 查看器开源许可', eyebrow: '从画稿走向立体', heading: '换个角度认识她', feature: '3D 角色预览', open: '探索 3D 形象',
    teaser: '转动、放大，细看角色的立体造型。模型与图片的来源、许可分别记录。',
    load: '加载 3D 预览', loading: '正在准备 3D 预览…', ready: '3D 预览已加载，可用下方按钮或直接拖动查看。',
    idle: '点击后才会下载 3D 文件；静态预览图始终可用。', error: '3D 预览未能加载。你仍可查看静态图、模型说明和来源，也可重试。', retry: '重试加载',
    instructions: '拖动可旋转，双指可缩放。也可用下方按钮：Tab 切换，Enter 或空格操作。',
    left: '向左转', right: '向右转', up: '从上方看', down: '从下方看', zoomIn: '放大', zoomOut: '缩小', reset: '重置视角', controls: '3D 视角控制',
    showPoster: '返回静态图', version: '版本', preview: '原型预览', released: '已审核', reviewed: '审核日期',
    license: '模型许可', attribution: '模型署名', source: '查看模型来源', changes: '制作与变更',
    rights: '3D 模型独立遵循下列许可与署名，不由本站代码许可或角色图片许可替代。',
    prototype: '这是制作中的 3D 原型，造型与细节仍可能调整。', downloadSize: '3D 文件', noScript: '启用 JavaScript 后可交互查看；静态图和来源信息不受影响。',
    portrait: '静态模型预览', resetDone: '已恢复初始视角。', moved: '视角已更新。', posterDone: '已返回静态预览图。',
    roles: { 'original-character': '原角色作者', 'secondary-design': '二创设计', 'model-author': '模型作者', 'model-adapter': '模型加工', 'published-adaptation': '发布与加工', publisher: '发布者' },
  },
  en: {
    notice: 'Model notice & full credits', manifest: 'Model provenance manifest', viewerCredits: '3D viewer open-source licenses', eyebrow: 'A NEW DIMENSION', heading: 'Meet her from every angle', feature: '3D character preview', open: 'Explore in 3D',
    teaser: 'Rotate, zoom, and explore the character in three dimensions. Model provenance and permissions are recorded separately from the artwork.',
    load: 'Load 3D preview', loading: 'Preparing the 3D preview…', ready: '3D preview loaded. Use the buttons below or drag to explore.',
    idle: 'The 3D file downloads only when you choose to load it. The still preview stays available.', error: 'The 3D preview could not load. The still image, model notes, and source remain available. You can try again.', retry: 'Try loading again',
    instructions: 'Drag to rotate; pinch to zoom. Or use the buttons below: Tab to move, Enter or Space to activate.',
    left: 'Rotate left', right: 'Rotate right', up: 'View from above', down: 'View from below', zoomIn: 'Zoom in', zoomOut: 'Zoom out', reset: 'Reset view', controls: '3D view controls',
    showPoster: 'Return to still image', version: 'Version', preview: 'Prototype preview', released: 'Reviewed model', reviewed: 'Reviewed',
    license: 'Model license', attribution: 'Model credits', source: 'View model source', changes: 'Making & changes',
    rights: 'This 3D model has its own license and credits below. The site code license and character artwork permissions do not replace them.',
    prototype: 'This is a work-in-progress 3D prototype. Its shape and details may change.', downloadSize: '3D file', noScript: 'Enable JavaScript for interaction. The still image and provenance remain available.',
    portrait: 'Still model preview', resetDone: 'Starting view restored.', moved: 'View updated.', posterDone: 'Returned to the still preview.',
    roles: { 'original-character': 'Original character creator', 'secondary-design': 'Derivative designer', 'model-author': 'Model creator', 'model-adapter': 'Model adapter', 'published-adaptation': 'Publisher / adapter', publisher: 'Publisher' },
  },
  ja: {
    notice: 'モデルの声明・全クレジット', manifest: 'モデルの出典記録', viewerCredits: '3D ビューアーのオープンソースライセンス', eyebrow: 'イラストから立体へ', heading: 'いろいろな角度から会ってみよう', feature: '3D キャラクタープレビュー', open: '3D で見る',
    teaser: '回転・拡大して、キャラクターの立体的な姿を楽しめます。モデルの出典・利用条件は画像と分けて記録しています。',
    load: '3D プレビューを読み込む', loading: '3D プレビューを準備中…', ready: '3D プレビューを読み込みました。下のボタンまたはドラッグで操作できます。',
    idle: '操作を選ぶまで 3D ファイルはダウンロードされません。静止画はいつでも表示できます。', error: '3D プレビューを読み込めませんでした。静止画・モデルの説明・出典は引き続き確認できます。再試行もできます。', retry: 'もう一度読み込む',
    instructions: 'ドラッグで回転、ピンチで拡大・縮小。下のボタンは Tab で移動し、Enter またはスペースで操作できます。',
    left: '左へ回転', right: '右へ回転', up: '上から見る', down: '下から見る', zoomIn: '拡大', zoomOut: '縮小', reset: '視点をリセット', controls: '3D 視点の操作',
    showPoster: '静止画に戻る', version: 'バージョン', preview: '試作プレビュー', released: '確認済みモデル', reviewed: '確認日',
    license: 'モデルの利用条件', attribution: 'モデルのクレジット', source: 'モデルの出典を見る', changes: '制作・変更内容',
    rights: 'この 3D モデルには以下の固有の利用条件とクレジットが適用されます。サイトのコードやキャラクター画像の許諾で置き換えることはできません。',
    prototype: '制作中の 3D 試作です。形状や細部は今後変更される場合があります。', downloadSize: '3D ファイル', noScript: '操作するには JavaScript を有効にしてください。静止画と出典情報はそのまま確認できます。',
    portrait: 'モデルの静止画プレビュー', resetDone: '最初の視点に戻りました。', moved: '視点を更新しました。', posterDone: '静止画プレビューに戻りました。',
    roles: { 'original-character': 'キャラクター原作者', 'secondary-design': '二次デザイン', 'model-author': 'モデル作者', 'model-adapter': 'モデル加工', 'published-adaptation': '公開・加工', publisher: '公開者' },
  },
} as const;
