export const studioText = {
  zh: {
    intro: '先选用途，再调尺寸。完整图像与署名分区展示，预览即导出；图片只在浏览器本地处理。',
    purpose: '这次想怎么用？', full: '完整立绘 · 768 × 1024', avatar: '头像画布 · 512 × 512', card: '角色介绍卡 · 768 × 1024', custom: '自定义',
    advanced: '高级参数', presetNote: '尺寸是本站默认值。调整高级参数会切换为自定义；始终保留完整图像与署名区。',
    unavailable: '未确认相应排版与再分享用途的预设不可选。', blocked: '此作品尚未确认该用途，请选择可用预设。',
    result: '成品尺寸包含署名区；请连同署名和来源一起分享。放大不会恢复细节。',
    export: '导出成品与来源 ZIP', contains: '包含：带署名的成品图片、原始文件、使用条件、来源与处理记录。',
    sourceType: '本地图片来源', publicSource: '已有公开来源', unpublished: '本人原创、尚未公开发布',
    source: '原始发布链接（必填，HTTPS）', author: '作者（必填）', terms: '使用条件或本人使用声明（必填）',
    required: '请填写作者、使用声明；公开来源还需要有效的 HTTPS 来源链接。',
    originalConfirm: '我确认这是本人原创、尚未公开发布的作品，并有权加工、排版和分享。',
    originalRequired: '请确认本人原创且尚未公开发布，并填写作者与使用声明。',
    compositionConsent: '我已确认有权将此图与文字排版并再分享。',
    unverified: '用户自述，未经独立核验；仅进入本地导出包，不会收录到公开库。',
    localSession: '刷新或切换语言后，需要重新选择本地图片并填写来源信息。',
    unpublishedCredit: '本人原创、尚未公开发布（用户自述，未经独立核验）',
    publicCredit: '公开来源与条件由用户提供，未经独立核验',
    title: '介绍卡标题', titleHint: '只描述你的用途，不代表官方设定。',
    credit: '成品署名与来源', copy: '复制署名与来源', copied: '署名与来源已复制', copyFailed: '自动复制失败，请手动复制下方文字。',
    changes: '处理：完整图像等比适配、留白、格式转换；署名区独立排版。',
    cardChanges: '处理：完整图像等比适配，另加标题与署名区。',
    cc: '非商业 · 保留完整署名 · 派生作品相同方式共享 · 无担保',
    creator: '作者条件：署名 ZipZipPipe，不可商用；仅技术处理。',
    layoutError: '署名或声明放不下，请增大画布或缩短本地填写的文字。不会裁去文字或图像。',
    evidenceError: '来源文件无法读取或校验不一致，未生成导出包。请重试。',
    changed: '素材已改变，请检查新预览后重新导出。',
  },
  en: {
    intro: 'Choose a use, then adjust the size. The full image and credits occupy separate areas; export matches the preview. Images stay in your browser.',
    purpose: 'What are you making?', full: 'Full portrait · 768 × 1024', avatar: 'Avatar canvas · 512 × 512', card: 'Introduction card · 768 × 1024', custom: 'Custom',
    advanced: 'Advanced settings', presetNote: 'These are site defaults. Changing advanced settings switches to Custom; the full image and credit area are always retained.',
    unavailable: 'Presets without confirmed layout and resharing permission are unavailable.', blocked: 'This artwork has not been reviewed for this use. Choose an available preset.',
    result: 'Output dimensions include the credit area. Share the image with its credits and source intact. Upscaling does not recover detail.',
    export: 'Export image and provenance ZIP', contains: 'Includes a credited image, original bytes, terms, source and processing records.',
    sourceType: 'Local image source', publicSource: 'Already published', unpublished: 'My original, not yet published',
    source: 'Original publication URL (HTTPS required)', author: 'Creator (required)', terms: 'Usage terms or my usage statement (required)',
    required: 'Add the creator and usage statement; a published image also needs a valid HTTPS source URL.',
    originalConfirm: 'I confirm this is my original, unpublished work and I have the right to process, arrange and share it.',
    originalRequired: 'Confirm your original, unpublished work and provide the creator and usage statement.',
    compositionConsent: 'I have confirmed permission to arrange this image with text and reshare it.',
    unverified: 'Self-declared, not independently verified. Included only in the local export, never added to the public atlas.',
    localSession: 'After a reload or language change, select the local image and enter its source information again.',
    unpublishedCredit: 'Original, unpublished work (self-declared; not independently verified)',
    publicCredit: 'Public source and terms supplied by the user; not independently verified',
    title: 'Card title', titleHint: 'Describe your use; this is not official character lore.',
    credit: 'Image credits and source', copy: 'Copy credits and source', copied: 'Credits and source copied', copyFailed: 'Automatic copy failed. Copy the text below manually.',
    changes: 'Processing: full-image fitting, padding and format conversion; separate credit area.',
    cardChanges: 'Processing: full-image fitting with a separate title and credit area.',
    cc: 'Non-commercial · Full attribution · ShareAlike for adaptations · No warranties',
    creator: 'Creator terms: credit ZipZipPipe; non-commercial; technical processing only.',
    layoutError: 'Credits or statements do not fit. Increase the canvas size or shorten local text. Nothing will be cropped.',
    evidenceError: 'A source file could not be read or its hash did not match. No export was generated. Please retry.',
    changed: 'The asset changed. Check the new preview and export again.',
  },
  ja: {
    intro: '用途を選び、サイズを調整。画像全体とクレジットを別の領域に配置し、プレビューと同じ画像を書き出します。画像はブラウザ内で処理されます。',
    purpose: 'どのように使いますか？', full: '全身立ち絵 · 768 × 1024', avatar: 'アイコン用キャンバス · 512 × 512', card: '紹介カード · 768 × 1024', custom: 'カスタム',
    advanced: '詳細設定', presetNote: 'サイズは当サイトの初期値です。詳細設定を変更するとカスタムに切り替わります。画像全体とクレジット欄は常に保持します。',
    unavailable: 'レイアウト・再共有の用途が未確認のプリセットは選択できません。', blocked: 'この作品では用途が未確認です。利用可能なプリセットを選んでください。',
    result: '出力サイズにはクレジット欄を含みます。出典・クレジットを残して共有してください。拡大は細部の復元ではありません。',
    export: '画像と出典を ZIP で保存', contains: 'クレジット付き画像、元ファイル、利用条件、出典・加工記録を同梱します。',
    sourceType: 'ローカル画像の出典', publicSource: '公開済みの作品', unpublished: '本人の未公開オリジナル作品',
    source: '元の公開 URL（HTTPS・必須）', author: '作者（必須）', terms: '利用条件または本人の利用声明（必須）',
    required: '作者と利用声明を入力してください。公開済み画像には有効な HTTPS の出典 URL も必要です。',
    originalConfirm: 'これは本人の未公開オリジナル作品であり、加工・レイアウト・共有の権利を有することを確認します。',
    originalRequired: '本人の未公開オリジナル作品であることを確認し、作者と利用声明を入力してください。',
    compositionConsent: '画像を文字と組み合わせて再共有する許可を確認しました。',
    unverified: 'ユーザーの自己申告であり、独立検証は未実施。ローカルの出力にのみ含め、公開図鑑には収録しません。',
    localSession: '再読み込み・言語切り替え後はローカル画像と出典情報を再入力してください。',
    unpublishedCredit: '本人の未公開オリジナル作品（自己申告・独立検証なし）',
    publicCredit: '公開出典・条件はユーザー提供、独立検証なし',
    title: '紹介カードの見出し', titleHint: '自分の用途を記載してください。公式設定を示すものではありません。',
    credit: '画像のクレジットと出典', copy: 'クレジットと出典をコピー', copied: 'クレジットと出典をコピーしました', copyFailed: '自動コピーできません。下の文字を手動でコピーしてください。',
    changes: '加工：画像全体の比率維持リサイズ・余白・形式変換。クレジットは別領域に配置。',
    cardChanges: '加工：画像全体の比率維持リサイズ。見出しとクレジットを別領域に配置。',
    cc: '非商用・全作者を明記・派生物は同一条件で共有・無保証',
    creator: '作者の条件：ZipZipPipe の明記・非商用・技術的処理のみ。',
    layoutError: 'クレジットや声明が収まりません。サイズを大きくするか入力文を短くしてください。文字や画像は切り取りません。',
    evidenceError: '出典ファイルを読み込めないかハッシュが一致しないため、出力を作成しませんでした。再試行してください。',
    changed: '素材が変わりました。新しいプレビューを確認して再度書き出してください。',
  },
};
